export const routes = {
  ESTIMATE_SERVICE: '/estimates',
  ESTIMATE_DETAIL: '/estimates/detail/:id',
  ORDER_SERVICE: '/orders',
  ORDER_DETAIL: '/orders/detail/:id',
  DIAGNOSTIC: '/diagnostics',
  VEHICULES: '/vehicules',
  CLIENTS: '/clients',
  LOGIN: '/login',
  MAIN: '/',
}

export const Endpoints = {
  GET_ALL_ESTIMATIONS: 'estimate/all',
  GET_ALL_VEHICULE: 'vehicule/getAll',
  GET_ALL_BRAND_MODEL: 'vehicule/getAll/brands',
  GET_ALL_CLIENTS: 'clients/getAll',
  GET_ALL_CLIENTS_WITH_CARS: 'clients/getAllWithCars',
  ASSIGN_VEHICULE_TO_CLIENT: 'vehicule/assignVehiculeToClient',
  CREATE_ESTIMATION: '/estimate/create',
  CREATE_CLIENT: 'clients/create',
  CREATE_VEHICULE: 'vehicule/create',
  CREATE_VEHICULE_BRAND: 'vehicule/create/brand',
  CREATE_MULTIPLE_BRANDS: 'vehicule/create/multiple/models',
  LOGIN: 'auth/',
  GET_ESTIMATION_DETAIL_BY_ID: '/estimate/detail/',
  GET_ESTIMATION_ORDER_DETAIL_BY_ID: '/estimate/detailWithOrder/',
  GET_ORDER_DETAIL_SERVICE: '/order/detail/',
  GET_ALL_ORDERS: '/order/getAll',
  CREATE_ORDER_SERVICE: '/order/create/',
}